apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: default
  labels:
    app: store-front
    istio: proxy                   # Prometheus match tag
    security.istio.io/tlsMode: istio   # Important for ServiceMonitor match
spec:
  type: NodePort
  selector:
    app: store-front
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: http-envoy-prom        # ðŸ‘ˆ must be EXACT name
      port: 15090
      targetPort: 15090
