apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: ghcr.io/azure-samples/aks-store-demo/store-admin:latest
          ports:
            - containerPort: 8081   # <-- change to 8081
